# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(582, 600)
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 60, 63, 20))
        self.input_dir = QLineEdit(Widget)
        self.input_dir.setObjectName(u"input_dir")
        self.input_dir.setGeometry(QRect(40, 90, 113, 28))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 130, 63, 20))
        self.output_dir = QLineEdit(Widget)
        self.output_dir.setObjectName(u"output_dir")
        self.output_dir.setGeometry(QRect(40, 160, 113, 28))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 270, 63, 20))
        self.drio_dir = QLineEdit(Widget)
        self.drio_dir.setObjectName(u"drio_dir")
        self.drio_dir.setGeometry(QRect(40, 300, 113, 28))
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 380, 111, 20))
        self.dict_dir = QLineEdit(Widget)
        self.dict_dir.setObjectName(u"dict_dir")
        self.dict_dir.setGeometry(QRect(40, 410, 113, 28))
        self.dumb = QCheckBox(Widget)
        self.dumb.setObjectName(u"dumb")
        self.dumb.setGeometry(QRect(40, 340, 111, 26))
        self.time_limit = QLineEdit(Widget)
        self.time_limit.setObjectName(u"time_limit")
        self.time_limit.setGeometry(QRect(40, 230, 113, 28))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 200, 81, 20))
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 270, 101, 20))
        self.fuzz_iter = QLineEdit(Widget)
        self.fuzz_iter.setObjectName(u"fuzz_iter")
        self.fuzz_iter.setGeometry(QRect(310, 300, 113, 28))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(310, 200, 111, 20))
        self.rva = QLineEdit(Widget)
        self.rva.setObjectName(u"rva")
        self.rva.setGeometry(QRect(310, 230, 113, 28))
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(310, 370, 111, 20))
        self.label_10 = QLabel(Widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(310, 130, 111, 20))
        self.trg_module = QLineEdit(Widget)
        self.trg_module.setObjectName(u"trg_module")
        self.trg_module.setGeometry(QRect(310, 160, 113, 28))
        self.label_11 = QLabel(Widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(310, 340, 121, 20))
        self.dbg_checkbox = QCheckBox(Widget)
        self.dbg_checkbox.setObjectName(u"dbg_checkbox")
        self.dbg_checkbox.setGeometry(QRect(310, 440, 111, 26))
        self.out_label = QLabel(Widget)
        self.out_label.setObjectName(u"out_label")
        self.out_label.setGeometry(QRect(310, 60, 131, 20))
        self.out_file = QLineEdit(Widget)
        self.out_file.setObjectName(u"out_file")
        self.out_file.setGeometry(QRect(310, 90, 113, 28))
        self.in_button = QPushButton(Widget)
        self.in_button.setObjectName(u"in_button")
        self.in_button.setGeometry(QRect(170, 90, 83, 29))
        self.out_button = QPushButton(Widget)
        self.out_button.setObjectName(u"out_button")
        self.out_button.setGeometry(QRect(170, 160, 83, 29))
        self.dict_button = QPushButton(Widget)
        self.dict_button.setObjectName(u"dict_button")
        self.dict_button.setGeometry(QRect(170, 410, 83, 29))
        self.drio_button = QPushButton(Widget)
        self.drio_button.setObjectName(u"drio_button")
        self.drio_button.setGeometry(QRect(170, 300, 83, 29))
        self.trg_button = QPushButton(Widget)
        self.trg_button.setObjectName(u"trg_button")
        self.trg_button.setGeometry(QRect(440, 160, 83, 29))
        self.outf_button = QPushButton(Widget)
        self.outf_button.setObjectName(u"outf_button")
        self.outf_button.setGeometry(QRect(440, 90, 83, 29))
        self.call_conv = QComboBox(Widget)
        self.call_conv.setObjectName(u"call_conv")
        self.call_conv.setGeometry(QRect(310, 400, 111, 28))
        self.args = QSpinBox(Widget)
        self.args.setObjectName(u"args")
        self.args.setGeometry(QRect(440, 340, 48, 21))
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(270, 50, 20, 501))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_13 = QLabel(Widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(310, 20, 171, 20))
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(310, 470, 111, 20))
        self.log_dir = QLineEdit(Widget)
        self.log_dir.setObjectName(u"log_dir")
        self.log_dir.setEnabled(False)
        self.log_dir.setGeometry(QRect(310, 500, 113, 28))
        self.log_button = QPushButton(Widget)
        self.log_button.setObjectName(u"log_button")
        self.log_button.setEnabled(False)
        self.log_button.setGeometry(QRect(440, 500, 83, 29))
        self.line_2 = QFrame(Widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(280, 40, 281, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(Widget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(550, 50, 20, 501))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(Widget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(280, 540, 281, 21))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(Widget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(20, 40, 261, 21))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_14 = QLabel(Widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(50, 20, 131, 20))
        self.line_6 = QFrame(Widget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(20, 540, 261, 21))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(Widget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 50, 20, 501))
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.distrib_mode = QCheckBox(Widget)
        self.distrib_mode.setObjectName(u"distrib_mode")
        self.distrib_mode.setGeometry(QRect(40, 450, 151, 26))
        self.fuzz_id = QLineEdit(Widget)
        self.fuzz_id.setObjectName(u"fuzz_id")
        self.fuzz_id.setEnabled(False)
        self.fuzz_id.setGeometry(QRect(40, 480, 113, 28))
        self.start_button = QPushButton(Widget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(480, 560, 75, 24))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Input dir", None))
        self.input_dir.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\in", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"output dir", None))
        self.output_dir.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\out", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"DRIO dir", None))
        self.drio_dir.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\DynamoRIO-2\\bin64", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Dictionary dir", None))
        self.dict_dir.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\dict", None))
        self.dumb.setText(QCoreApplication.translate("Widget", u"dumb mode", None))
        self.time_limit.setText(QCoreApplication.translate("Widget", u"40000", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Time limit", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Fuzz iterations", None))
        self.fuzz_iter.setText(QCoreApplication.translate("Widget", u"5000", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Target offset", None))
        self.rva.setText(QCoreApplication.translate("Widget", u"0x119A0", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Call-convetion", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"Target module", None))
        self.trg_module.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\Test1.exe", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Number of args", None))
        self.dbg_checkbox.setText(QCoreApplication.translate("Widget", u"Debug", None))
        self.out_label.setText(QCoreApplication.translate("Widget", u"Out file", None))
        self.out_file.setText(QCoreApplication.translate("Widget", u"D:\\AFL\\test.txt", None))
        self.in_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.out_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.dict_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.drio_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.trg_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.outf_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Instrumentation settings", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Log dir", None))
        self.log_button.setText(QCoreApplication.translate("Widget", u"Browse", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Fuzz settings", None))
        self.distrib_mode.setText(QCoreApplication.translate("Widget", u"Distributed mode", None))
        self.start_button.setText(QCoreApplication.translate("Widget", u"Start", None))
    # retranslateUi

